language: generic

before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
  - unzip terraform_0.11.7_linux_amd64.zip
 
#These two steps will effectively validate our terraform and output a list of any changes to be made to our infrastructure
script:
  - ./terraform init
  - ./terraform plan -var "variable=${env.aws_access_key}" "variable=${env.aws_secret_key}"

deploy:
#Roll out any terraform changes required
- provider: script
  script: 
    - ./terraform apply -auto-approve 
  skip_cleanup: true
  on:
    branch: master
    
 - provider: aws   
   access_key_id: $aws_access_key
  secret_access_key: $aws_secret_key
  on:
  branch: master
  
